import Vue from 'vue'
import { Button, Tabbar, TabbarItem, NavBar, Toast, Search, Swipe, SwipeItem, Grid, GridItem, Icon, Rate, GoodsAction, GoodsActionIcon, GoodsActionButton, Collapse, CollapseItem, ActionSheet, Dialog } from 'vant'

Vue.use(Dialog)
Vue.use(ActionSheet)
Vue.use(Collapse)
Vue.use(CollapseItem)
Vue.use(GoodsAction)
Vue.use(GoodsActionButton)
Vue.use(GoodsActionIcon)
Vue.use(Rate)
Vue.use(Icon)
Vue.use(Button)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(NavBar)
Vue.use(Toast)
Vue.use(Search)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Grid)
Vue.use(GridItem)
